channels:
- pytorch
- anaconda
- defaults
dependencies:
- conda=4.12.0
- pytorch::cpuonly=2.0
- anaconda::python=3.7.7
- pytorch::pytorch=1.5.0
- pytorch::torchvision=0.10.0
- pip:
  - future==0.18.2
  - numpy==1.20.2
  - pyyaml==6.0